import { Product, Review, Partner } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nashta',
    description: 'Nashta is a science-backed, all-natural breakfast mix designed to boost energy, brain development, and digestion. Using wholesome ingredients and Ayurvedic herbs, it offers a chemical-free, nutrient-dense alternative to sugary cereals',
    price: 2950,
    originalPrice: 3850,
    discountPercentage: 23,
    images: [
      require('../images/best seller/nashta.jpg'),
    ],
    category: 'Supplements',
    featured: true,
    bestSeller: true,
    stock: 45,
    tags: ['Organic', 'Premium', 'Saffron'],
  },
  {
    id: '2',
    name: 'Vitaman',
    description: 'Essential vitamin-rich organic supplement blend. Packed with natural nutrients to boost immunity and energy.',
    price: 3200,
    originalPrice: 4000,
    discountPercentage: 20,
    images: [
      require('../images/best seller/Vitaman.jpg'),
    ],
    category: 'Supplements',
    featured: true,
    bestSeller: true,
    stock: 32,
    tags: ['Organic', 'Immunity', 'Vitamins'],
  },
  {
    id: '3',
    name: 'Desi Ghee',
    description: 'Experience the rich, traditional taste of Organicles Pure Desi Ghee. Naturally packed with essential nutrients and healthy fats, our additive-free ghee provides a clean energy boost for your daily meals.',
    price: 4250,
    originalPrice: 5500,
    discountPercentage: 18,
    images: [
      require('../images/best seller/desi ghee.jpg'),
    ],
    category: 'Wellness',
    featured: true,
    bestSeller: true,
    stock: 28,
    tags: ['Himalayan', 'Pure', 'Energy'],
  },
  {
    id: '4',
    name: 'Zero Pain Oil',
    description: 'Raw unprocessed honey from mountain wildflowers. Rich flavor with natural enzymes and minerals.',
    price: 1800,
    originalPrice: 2200,
    discountPercentage: 18,
    images: [
      require('../images/best seller/zero pain oil.jpg'),
    ],
    category: 'Oils',
    featured: true,
    bestSeller: false,
    stock: 67,
    tags: ['Raw', 'Wildflower', 'Natural'],
  },
  {
    id: '5',
    name: 'Herbal Tea Blend',
    description: 'Carefully curated blend of organic herbs for relaxation and wellness. Caffeine-free and naturally soothing.',
    price: 1200,
    originalPrice: 1500,
    discountPercentage: 20,
    images: [
      'https://images.unsplash.com/photo-1597318130659-56283b41875f?w=400',
    ],
    category: 'Beverages',
    featured: false,
    bestSeller: false,
    stock: 89,
    tags: ['Herbal', 'Caffeine-free', 'Relaxing'],
  },
  {
    id: '6',
    name: 'Moringa Powder',
    description: 'Premium organic moringa leaf powder. Superfood packed with vitamins, minerals, and antioxidants.',
    price: 2100,
    originalPrice: 2600,
    images: [
      require('../images/other products/moringa.jpg'),
    ],
    category: 'Supplements',
    featured: false,
    bestSeller: false,
    stock: 54,
    tags: ['Superfood', 'Organic', 'Powder'],
  },
  {
    id: '7',
    name: 'Olive Oil',
    description: 'Cold-pressed olive oil for everyday cooking and salads.',
    price: 1900,
    originalPrice: 2300,
    discountPercentage: 17,
    images: [
      require('../images/other products/olive oil 2.jpg'),
    ],
    category: 'Oils',
    featured: false,
    bestSeller: false,
    stock: 40,
    tags: ['Cold-pressed', 'Cooking'],
  },
  {
    id: '8',
    name: 'Brown Sugar',
    description: 'Natural brown sugar with rich caramel notes.',
    price: 650,
    originalPrice: 800,
    discountPercentage: 19,
    images: [
      require('../images/other products/brown sugar.jpg'),
    ],
    category: 'Sweeteners',
    featured: false,
    bestSeller: false,
    stock: 80,
    tags: ['Natural', 'Sweetener'],
  },
  {
    id: '9',
    name: 'Turmeric',
    description: 'Pure turmeric powder for golden milk and cooking.',
    price: 550,
    originalPrice: 700,
    discountPercentage: 21,
    images: [
      require('../images/other products/turmeric.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 70,
    tags: ['Spice', 'Organic'],
  },
  {
    id: '10',
    name: 'Spices Mix',
    description: 'Aromatic spice mix for rich flavor.',
    price: 900,
    originalPrice: 1100,
    discountPercentage: 18,
    images: [
      require('../images/other products/spices opt. 2.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 55,
    tags: ['Blend', 'Spice'],
  },
  {
    id: '11',
    name: 'Black Pepper',
    description: 'Fresh black pepper with bold aroma.',
    price: 750,
    originalPrice: 900,
    discountPercentage: 17,
    images: [
      require('../images/other products/black pepper.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 65,
    tags: ['Spice', 'Whole'],
  },
  {
    id: '12',
    name: 'Pink Salt',
    description: 'Mineral-rich pink salt for everyday use.',
    price: 500,
    originalPrice: 650,
    discountPercentage: 23,
    images: [
      require('../images/other products/pink salt.jpg'),
    ],
    category: 'Seasoning',
    featured: false,
    bestSeller: false,
    stock: 90,
    tags: ['Mineral', 'Salt'],
  },
  {
    id: '13',
    name: 'Chia Seeds',
    description: 'Chia seeds packed with fiber and omega-3.',
    price: 1200,
    originalPrice: 1500,
    discountPercentage: 20,
    images: [
      require('../images/other products/chia seed.jpg'),
    ],
    category: 'Seeds',
    featured: false,
    bestSeller: false,
    stock: 60,
    tags: ['Omega-3', 'Fiber'],
  },
  {
    id: '14',
    name: 'Methi Dana',
    description: 'Fenugreek seeds for cooking and wellness.',
    price: 450,
    originalPrice: 600,
    discountPercentage: 25,
    images: [
      require('../images/other products/methi dana.jpg'),
    ],
    category: 'Seeds',
    featured: false,
    bestSeller: false,
    stock: 75,
    tags: ['Fenugreek', 'Seeds'],
  },
  {
    id: '15',
    name: 'Organic Honey',
    description: 'Raw unprocessed honey from mountain wildflowers.',
    price: 1800,
    originalPrice: 2200,
    discountPercentage: 18,
    images: [
      require('../images/other products/honey.jpg'),
    ],
    category: 'Sweeteners',
    featured: false,
    bestSeller: false,
    stock: 67,
    tags: ['Raw', 'Wildflower', 'Natural'],
  },
  {
    id: '16',
    name: 'Clove',
    description: 'Whole cloves with warm, sweet aroma.',
    price: 800,
    originalPrice: 950,
    discountPercentage: 16,
    images: [
      require('../images/other products/clove.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 50,
    tags: ['Spice', 'Whole'],
  },
  {
    id: '17',
    name: 'Cardamom',
    description: 'Green cardamom pods for tea and desserts.',
    price: 1400,
    originalPrice: 1700,
    discountPercentage: 18,
    images: [
      require('../images/other products/cardamom.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 45,
    tags: ['Spice', 'Aromatic'],
  },
  {
    id: '18',
    name: 'Cinnamon',
    description: 'Cinnamon sticks with sweet, woody flavor.',
    price: 900,
    originalPrice: 1100,
    discountPercentage: 18,
    images: [
      require('../images/other products/cinnamon.jpg'),
    ],
    category: 'Spices',
    featured: false,
    bestSeller: false,
    stock: 55,
    tags: ['Spice', 'Sticks'],
  },
  {
    id: '19',
    name: 'Shilajit',
    description: 'Pure Himalayan Shilajit resin.',
    price: 4500,
    originalPrice: 5500,
    discountPercentage: 18,
    images: [
      require('../images/other products/shilajit.jpg'),
    ],
    category: 'Wellness',
    featured: false,
    bestSeller: false,
    stock: 28,
    tags: ['Himalayan', 'Pure', 'Energy'],
  },
  {
    id: '20',
    name: 'Coconut Oil',
    description: 'Cold-pressed coconut oil for cooking and skin.',
    price: 1600,
    originalPrice: 2000,
    discountPercentage: 20,
    images: [
      require('../images/other products/coconut oil.jpg'),
    ],
    category: 'Oils',
    featured: false,
    bestSeller: false,
    stock: 58,
    tags: ['Cold-pressed', 'Multi-use'],
  },
  
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    userName: 'Ayesha Khan',
    rating: 5,
    comment: 'Excellent quality! The Zafrani Nashta has improved my morning routine. Highly recommend Organicles products.',
    date: '2026-01-15',
  },
  {
    id: '2',
    userName: 'Ahmed Ali',
    rating: 5,
    comment: 'Genuine organic products at great prices. Fast delivery and well-packaged. Will order again!',
    date: '2026-01-20',
  },
  {
    id: '3',
    userName: 'Fatima Hassan',
    rating: 4,
    comment: 'Good quality Shilajit. Noticed improvement in energy levels after regular use. Packaging could be better.',
    date: '2026-01-22',
  },
  {
    id: '4',
    userName: 'Mohammad Raza',
    rating: 5,
    comment: 'Best organic store in Pakistan! Authentic products and excellent customer service. Keep it up!',
    date: '2026-01-25',
  },
];

export const MOCK_PARTNERS: Partner[] = [
  {
    id: '1',
    name: 'Organic Certification Board',
    logo: 'https://via.placeholder.com/100x50/2D5016/FFFFFF?text=OCB',
  },
  {
    id: '2',
    name: 'Natural Health Association',
    logo: 'https://via.placeholder.com/100x50/4A7C2B/FFFFFF?text=NHA',
  },
  {
    id: '3',
    name: 'Pure Foods Pakistan',
    logo: 'https://via.placeholder.com/100x50/2D5016/FFFFFF?text=PFP',
  },
  {
    id: '4',
    name: 'Wellness Council',
    logo: 'https://via.placeholder.com/100x50/4A7C2B/FFFFFF?text=WC',
  },
  {
    id: '5',
    name: 'Green Living Initiative',
    logo: 'https://via.placeholder.com/100x50/2D5016/FFFFFF?text=GLI',
  },
];
